version: '3.8'
services:
  app:
    build:
      args:
        user: admin
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: teqman
    container_name: teqman-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - teqman
  db:
    image: mysql:5.7
    container_name: teqman-db
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./.Docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - teqman
  nginx:
    image: nginx:1.17-alpine
    container_name: teqman-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./.Docker/nginx:/etc/nginx/conf.d
    networks:
      - teqman
networks:
  teqman:
    driver: bridge
